apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend-dr
  namespace: mrm-project
spec:
  host: backend-service
  # Настройки устойчивости для всего сервиса (Circuit Breaker)
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 10s
      baseEjectionTime: 30s
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend-vs
  namespace: mrm-project
spec:
  hosts:
  - backend-service
  http:
  - route:
    - destination:
        host: backend-service
        subset: v1
      weight: 80
    - destination:
        host: backend-service
        subset: v2
      weight: 20
    # Настройки автоматических повторов (Retries)
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: 5xx,connect-failure
