apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mrm-project
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mrm-frontend:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mrm-project
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
