apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: mrm-project
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-v1 # Следим за первой версией
  minReplicas: 1
  maxReplicas: 5    # Разрешаем разрастаться до 5 подов
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # Если CPU загружен > 50%, создаем новый под
